//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meta4IntegracionVioncereWS.VincereWSMeta4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vincere.com", ConfigurationName="VincereWSMeta4.VincereWebServiceMeta4")]
    public interface VincereWebServiceMeta4 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppResponse meta4GetInfoUserApp(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionResponse meta4ControlSession(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoResponse meta4GetFichaEmpleado(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosResponse meta4GetListaEmpleados(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutResponse meta4Logout(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhResponse meta4AddFavoriteRh(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhResponse meta4DelFavoriteRh(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserResponse meta4DelFileUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoResponse meta4SaveFileLeido(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserResponse meta4GetListaFilesUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserResponse meta4GetRealFileUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionResponse meta4DelNotificacion(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaResponse meta4SaveNotificacionLeida(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Meta4SessionId del espacio de nombres http://vincere.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesResponse meta4GetListaNotificaciones(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetInfoUserAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetInfoUserApp", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequestBody Body;
        
        public meta4GetInfoUserAppRequest() {
        }
        
        public meta4GetInfoUserAppRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetInfoUserAppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        public meta4GetInfoUserAppRequestBody() {
        }
        
        public meta4GetInfoUserAppRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetInfoUserAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetInfoUserAppResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppResponseBody Body;
        
        public meta4GetInfoUserAppResponse() {
        }
        
        public meta4GetInfoUserAppResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetInfoUserAppResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetInfoUserAppReturn;
        
        public meta4GetInfoUserAppResponseBody() {
        }
        
        public meta4GetInfoUserAppResponseBody(string meta4GetInfoUserAppReturn) {
            this.meta4GetInfoUserAppReturn = meta4GetInfoUserAppReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4ControlSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4ControlSession", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequestBody Body;
        
        public meta4ControlSessionRequest() {
        }
        
        public meta4ControlSessionRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4ControlSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        public meta4ControlSessionRequestBody() {
        }
        
        public meta4ControlSessionRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4ControlSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4ControlSessionResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionResponseBody Body;
        
        public meta4ControlSessionResponse() {
        }
        
        public meta4ControlSessionResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4ControlSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4ControlSessionReturn;
        
        public meta4ControlSessionResponseBody() {
        }
        
        public meta4ControlSessionResponseBody(string meta4ControlSessionReturn) {
            this.meta4ControlSessionReturn = meta4ControlSessionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetFichaEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetFichaEmpleado", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequestBody Body;
        
        public meta4GetFichaEmpleadoRequest() {
        }
        
        public meta4GetFichaEmpleadoRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetFichaEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string IdEmpleadoMeta4;
        
        public meta4GetFichaEmpleadoRequestBody() {
        }
        
        public meta4GetFichaEmpleadoRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.IdEmpleadoMeta4 = IdEmpleadoMeta4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetFichaEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetFichaEmpleadoResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoResponseBody Body;
        
        public meta4GetFichaEmpleadoResponse() {
        }
        
        public meta4GetFichaEmpleadoResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetFichaEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetFichaEmpleadoReturn;
        
        public meta4GetFichaEmpleadoResponseBody() {
        }
        
        public meta4GetFichaEmpleadoResponseBody(string meta4GetFichaEmpleadoReturn) {
            this.meta4GetFichaEmpleadoReturn = meta4GetFichaEmpleadoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaEmpleados", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequestBody Body;
        
        public meta4GetListaEmpleadosRequest() {
        }
        
        public meta4GetListaEmpleadosRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaEmpleadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string filters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double paginaDatos;
        
        public meta4GetListaEmpleadosRequestBody() {
        }
        
        public meta4GetListaEmpleadosRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string filters, double paginaDatos) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.filters = filters;
            this.paginaDatos = paginaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaEmpleadosResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosResponseBody Body;
        
        public meta4GetListaEmpleadosResponse() {
        }
        
        public meta4GetListaEmpleadosResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaEmpleadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetListaEmpleadosReturn;
        
        public meta4GetListaEmpleadosResponseBody() {
        }
        
        public meta4GetListaEmpleadosResponseBody(string meta4GetListaEmpleadosReturn) {
            this.meta4GetListaEmpleadosReturn = meta4GetListaEmpleadosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4Logout", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequestBody Body;
        
        public meta4LogoutRequest() {
        }
        
        public meta4LogoutRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        public meta4LogoutRequestBody() {
        }
        
        public meta4LogoutRequestBody(string Meta4SessionId) {
            this.Meta4SessionId = Meta4SessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4LogoutResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutResponseBody Body;
        
        public meta4LogoutResponse() {
        }
        
        public meta4LogoutResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int meta4LogoutReturn;
        
        public meta4LogoutResponseBody() {
        }
        
        public meta4LogoutResponseBody(int meta4LogoutReturn) {
            this.meta4LogoutReturn = meta4LogoutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4AddFavoriteRhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4AddFavoriteRh", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequestBody Body;
        
        public meta4AddFavoriteRhRequest() {
        }
        
        public meta4AddFavoriteRhRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4AddFavoriteRhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string IdEmpleadoMeta4;
        
        public meta4AddFavoriteRhRequestBody() {
        }
        
        public meta4AddFavoriteRhRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.IdEmpleadoMeta4 = IdEmpleadoMeta4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4AddFavoriteRhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4AddFavoriteRhResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhResponseBody Body;
        
        public meta4AddFavoriteRhResponse() {
        }
        
        public meta4AddFavoriteRhResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4AddFavoriteRhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double meta4AddFavoriteRhReturn;
        
        public meta4AddFavoriteRhResponseBody() {
        }
        
        public meta4AddFavoriteRhResponseBody(double meta4AddFavoriteRhReturn) {
            this.meta4AddFavoriteRhReturn = meta4AddFavoriteRhReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelFavoriteRhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelFavoriteRh", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequestBody Body;
        
        public meta4DelFavoriteRhRequest() {
        }
        
        public meta4DelFavoriteRhRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelFavoriteRhRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string IdEmpleadoMeta4;
        
        public meta4DelFavoriteRhRequestBody() {
        }
        
        public meta4DelFavoriteRhRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.IdEmpleadoMeta4 = IdEmpleadoMeta4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelFavoriteRhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelFavoriteRhResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhResponseBody Body;
        
        public meta4DelFavoriteRhResponse() {
        }
        
        public meta4DelFavoriteRhResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelFavoriteRhResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double meta4DelFavoriteRhReturn;
        
        public meta4DelFavoriteRhResponseBody() {
        }
        
        public meta4DelFavoriteRhResponseBody(double meta4DelFavoriteRhReturn) {
            this.meta4DelFavoriteRhReturn = meta4DelFavoriteRhReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelFileUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelFileUser", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequestBody Body;
        
        public meta4DelFileUserRequest() {
        }
        
        public meta4DelFileUserRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelFileUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalFile;
        
        public meta4DelFileUserRequestBody() {
        }
        
        public meta4DelFileUserRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalFile = OrdinalFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelFileUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelFileUserResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserResponseBody Body;
        
        public meta4DelFileUserResponse() {
        }
        
        public meta4DelFileUserResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelFileUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4DelFileUserReturn;
        
        public meta4DelFileUserResponseBody() {
        }
        
        public meta4DelFileUserResponseBody(string meta4DelFileUserReturn) {
            this.meta4DelFileUserReturn = meta4DelFileUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4SaveFileLeidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4SaveFileLeido", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequestBody Body;
        
        public meta4SaveFileLeidoRequest() {
        }
        
        public meta4SaveFileLeidoRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4SaveFileLeidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalFile;
        
        public meta4SaveFileLeidoRequestBody() {
        }
        
        public meta4SaveFileLeidoRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalFile = OrdinalFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4SaveFileLeidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4SaveFileLeidoResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoResponseBody Body;
        
        public meta4SaveFileLeidoResponse() {
        }
        
        public meta4SaveFileLeidoResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4SaveFileLeidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4SaveFileLeidoReturn;
        
        public meta4SaveFileLeidoResponseBody() {
        }
        
        public meta4SaveFileLeidoResponseBody(string meta4SaveFileLeidoReturn) {
            this.meta4SaveFileLeidoReturn = meta4SaveFileLeidoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaFilesUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaFilesUser", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequestBody Body;
        
        public meta4GetListaFilesUserRequest() {
        }
        
        public meta4GetListaFilesUserRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaFilesUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalFile;
        
        public meta4GetListaFilesUserRequestBody() {
        }
        
        public meta4GetListaFilesUserRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalFile = OrdinalFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaFilesUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaFilesUserResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserResponseBody Body;
        
        public meta4GetListaFilesUserResponse() {
        }
        
        public meta4GetListaFilesUserResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaFilesUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetListaFilesUserReturn;
        
        public meta4GetListaFilesUserResponseBody() {
        }
        
        public meta4GetListaFilesUserResponseBody(string meta4GetListaFilesUserReturn) {
            this.meta4GetListaFilesUserReturn = meta4GetListaFilesUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetRealFileUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetRealFileUser", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequestBody Body;
        
        public meta4GetRealFileUserRequest() {
        }
        
        public meta4GetRealFileUserRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetRealFileUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalFile;
        
        public meta4GetRealFileUserRequestBody() {
        }
        
        public meta4GetRealFileUserRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalFile = OrdinalFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetRealFileUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetRealFileUserResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserResponseBody Body;
        
        public meta4GetRealFileUserResponse() {
        }
        
        public meta4GetRealFileUserResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetRealFileUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetRealFileUserReturn;
        
        public meta4GetRealFileUserResponseBody() {
        }
        
        public meta4GetRealFileUserResponseBody(string meta4GetRealFileUserReturn) {
            this.meta4GetRealFileUserReturn = meta4GetRealFileUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelNotificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelNotificacion", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequestBody Body;
        
        public meta4DelNotificacionRequest() {
        }
        
        public meta4DelNotificacionRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelNotificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalNotificacion;
        
        public meta4DelNotificacionRequestBody() {
        }
        
        public meta4DelNotificacionRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalNotificacion = OrdinalNotificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4DelNotificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4DelNotificacionResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionResponseBody Body;
        
        public meta4DelNotificacionResponse() {
        }
        
        public meta4DelNotificacionResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4DelNotificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4DelNotificacionReturn;
        
        public meta4DelNotificacionResponseBody() {
        }
        
        public meta4DelNotificacionResponseBody(string meta4DelNotificacionReturn) {
            this.meta4DelNotificacionReturn = meta4DelNotificacionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4SaveNotificacionLeidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4SaveNotificacionLeida", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequestBody Body;
        
        public meta4SaveNotificacionLeidaRequest() {
        }
        
        public meta4SaveNotificacionLeidaRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4SaveNotificacionLeidaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalNotificacion;
        
        public meta4SaveNotificacionLeidaRequestBody() {
        }
        
        public meta4SaveNotificacionLeidaRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalNotificacion = OrdinalNotificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4SaveNotificacionLeidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4SaveNotificacionLeidaResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaResponseBody Body;
        
        public meta4SaveNotificacionLeidaResponse() {
        }
        
        public meta4SaveNotificacionLeidaResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4SaveNotificacionLeidaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4SaveNotificacionLeidaReturn;
        
        public meta4SaveNotificacionLeidaResponseBody() {
        }
        
        public meta4SaveNotificacionLeidaResponseBody(string meta4SaveNotificacionLeidaReturn) {
            this.meta4SaveNotificacionLeidaReturn = meta4SaveNotificacionLeidaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaNotificacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaNotificaciones", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequestBody Body;
        
        public meta4GetListaNotificacionesRequest() {
        }
        
        public meta4GetListaNotificacionesRequest(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaNotificacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Meta4SessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Base64Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dispositivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double OrdinalNotificacion;
        
        public meta4GetListaNotificacionesRequestBody() {
        }
        
        public meta4GetListaNotificacionesRequestBody(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            this.Meta4SessionId = Meta4SessionId;
            this.User = User;
            this.Base64Password = Base64Password;
            this.UUID = UUID;
            this.Dispositivo = Dispositivo;
            this.OrdinalNotificacion = OrdinalNotificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class meta4GetListaNotificacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="meta4GetListaNotificacionesResponse", Namespace="http://vincere.com", Order=0)]
        public Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesResponseBody Body;
        
        public meta4GetListaNotificacionesResponse() {
        }
        
        public meta4GetListaNotificacionesResponse(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://vincere.com")]
    public partial class meta4GetListaNotificacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meta4GetListaNotificacionesReturn;
        
        public meta4GetListaNotificacionesResponseBody() {
        }
        
        public meta4GetListaNotificacionesResponseBody(string meta4GetListaNotificacionesReturn) {
            this.meta4GetListaNotificacionesReturn = meta4GetListaNotificacionesReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VincereWebServiceMeta4Channel : Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VincereWebServiceMeta4Client : System.ServiceModel.ClientBase<Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4>, Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4 {
        
        public VincereWebServiceMeta4Client() {
        }
        
        public VincereWebServiceMeta4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VincereWebServiceMeta4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VincereWebServiceMeta4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VincereWebServiceMeta4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetInfoUserApp(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequest request) {
            return base.Channel.meta4GetInfoUserApp(request);
        }
        
        public string meta4GetInfoUserApp(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetInfoUserAppResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetInfoUserApp(inValue);
            return retVal.Body.meta4GetInfoUserAppReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4ControlSession(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequest request) {
            return base.Channel.meta4ControlSession(request);
        }
        
        public string meta4ControlSession(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4ControlSessionResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4ControlSession(inValue);
            return retVal.Body.meta4ControlSessionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetFichaEmpleado(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequest request) {
            return base.Channel.meta4GetFichaEmpleado(request);
        }
        
        public string meta4GetFichaEmpleado(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.IdEmpleadoMeta4 = IdEmpleadoMeta4;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetFichaEmpleadoResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetFichaEmpleado(inValue);
            return retVal.Body.meta4GetFichaEmpleadoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetListaEmpleados(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequest request) {
            return base.Channel.meta4GetListaEmpleados(request);
        }
        
        public string meta4GetListaEmpleados(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string filters, double paginaDatos) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.filters = filters;
            inValue.Body.paginaDatos = paginaDatos;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaEmpleadosResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetListaEmpleados(inValue);
            return retVal.Body.meta4GetListaEmpleadosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4Logout(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequest request) {
            return base.Channel.meta4Logout(request);
        }
        
        public int meta4Logout(string Meta4SessionId) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4LogoutResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4Logout(inValue);
            return retVal.Body.meta4LogoutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4AddFavoriteRh(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequest request) {
            return base.Channel.meta4AddFavoriteRh(request);
        }
        
        public double meta4AddFavoriteRh(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.IdEmpleadoMeta4 = IdEmpleadoMeta4;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4AddFavoriteRhResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4AddFavoriteRh(inValue);
            return retVal.Body.meta4AddFavoriteRhReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4DelFavoriteRh(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequest request) {
            return base.Channel.meta4DelFavoriteRh(request);
        }
        
        public double meta4DelFavoriteRh(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, string IdEmpleadoMeta4) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.IdEmpleadoMeta4 = IdEmpleadoMeta4;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFavoriteRhResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4DelFavoriteRh(inValue);
            return retVal.Body.meta4DelFavoriteRhReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4DelFileUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequest request) {
            return base.Channel.meta4DelFileUser(request);
        }
        
        public string meta4DelFileUser(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalFile = OrdinalFile;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelFileUserResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4DelFileUser(inValue);
            return retVal.Body.meta4DelFileUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4SaveFileLeido(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequest request) {
            return base.Channel.meta4SaveFileLeido(request);
        }
        
        public string meta4SaveFileLeido(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalFile = OrdinalFile;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveFileLeidoResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4SaveFileLeido(inValue);
            return retVal.Body.meta4SaveFileLeidoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetListaFilesUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequest request) {
            return base.Channel.meta4GetListaFilesUser(request);
        }
        
        public string meta4GetListaFilesUser(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalFile = OrdinalFile;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaFilesUserResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetListaFilesUser(inValue);
            return retVal.Body.meta4GetListaFilesUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetRealFileUser(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequest request) {
            return base.Channel.meta4GetRealFileUser(request);
        }
        
        public string meta4GetRealFileUser(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalFile) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalFile = OrdinalFile;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetRealFileUserResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetRealFileUser(inValue);
            return retVal.Body.meta4GetRealFileUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4DelNotificacion(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequest request) {
            return base.Channel.meta4DelNotificacion(request);
        }
        
        public string meta4DelNotificacion(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalNotificacion = OrdinalNotificacion;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4DelNotificacionResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4DelNotificacion(inValue);
            return retVal.Body.meta4DelNotificacionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4SaveNotificacionLeida(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequest request) {
            return base.Channel.meta4SaveNotificacionLeida(request);
        }
        
        public string meta4SaveNotificacionLeida(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalNotificacion = OrdinalNotificacion;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4SaveNotificacionLeidaResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4SaveNotificacionLeida(inValue);
            return retVal.Body.meta4SaveNotificacionLeidaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesResponse Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4.meta4GetListaNotificaciones(Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequest request) {
            return base.Channel.meta4GetListaNotificaciones(request);
        }
        
        public string meta4GetListaNotificaciones(string Meta4SessionId, string User, string Base64Password, string UUID, string Dispositivo, double OrdinalNotificacion) {
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequest inValue = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequest();
            inValue.Body = new Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesRequestBody();
            inValue.Body.Meta4SessionId = Meta4SessionId;
            inValue.Body.User = User;
            inValue.Body.Base64Password = Base64Password;
            inValue.Body.UUID = UUID;
            inValue.Body.Dispositivo = Dispositivo;
            inValue.Body.OrdinalNotificacion = OrdinalNotificacion;
            Meta4IntegracionVioncereWS.VincereWSMeta4.meta4GetListaNotificacionesResponse retVal = ((Meta4IntegracionVioncereWS.VincereWSMeta4.VincereWebServiceMeta4)(this)).meta4GetListaNotificaciones(inValue);
            return retVal.Body.meta4GetListaNotificacionesReturn;
        }
    }
}
